version: '2'

services:
  ssr-with-react-16:
    image: ssr-with-react-16
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/index.js
